# Derived from https://github.com/theochem/qcgrids/blob/master/.travis.yml
env:
  matrix:
  - MYCONDAPY=2.7
  - MYCONDAPY=3.5
  - MYCONDAPY=3.6

####
# EVERYTHING BELOW THIS LINE WILL BE COPIED INTO OTHER YMLs
####

# Do not use Travis Python to save some time.
language: generic
os:
- linux
- osx
osx_image: xcode6.4
dist: trusty
sudo: false

matrix:
  # We only test on Linux with one specific Python version, unless we make a release. All
  # other cases are allowed to fail and will exit early. With the fast_finish option,
  # travis will send a status update to github as soon as the non-allowed-to-fail has
  # finished. This speeds up testing in PRs.
  #
  # This is not ideal. It would be better to run just one item from the build matrix when
  # not preparing a release. This is not possible on Travis. There are several tickets on
  # travis-ci related to this limitation.
  #
  #    https://github.com/travis-ci/travis-ci/issues/7451
  #    https://github.com/travis-ci/travis-ci/issues/7149
  #    https://github.com/travis-ci/travis-ci/issues/2778
  #    ...
  fast_finish: true

cache:
  directories:
  - $HOME/download
  - $HOME/miniconda

before_cache:
- if [[ ! $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
- rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
- conda build purge

branches:
  only:
  - master
  - /^v[0-9]+\.[0-9]+(\.[0-9]+)?([abc][0-9]*)?$/  # release branches

before_install:
# Get miniconda. Take the right version, so re-installing python is hopefully not needed.
- if test -e $HOME/miniconda/bin; then
    echo "miniconda already installed.";
  else
    echo "Installing miniconda.";
    rm -rf $HOME/miniconda;
    mkdir -p $HOME/download;
    if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi;
    if [ "${MYCONDAPY}" = "2.7" ]; then
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
      fi;
    else
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
      fi;
    fi;
    bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
  fi


install:
- source $HOME/miniconda/bin/activate
- hash -r

# Configure conda and get a few essentials
- conda config --set always_yes yes
# Show conda info for debugging
- conda install -q conda conda-build
- conda config --add channels bioconda
- conda config --add channels omnia
- conda config --add channels insilichem
- conda info -a
- conda list
# Dependencies
- travis_wait conda build --python=${MYCONDAPY} devtools/conda-recipe
- if [[ $TRAVIS_TAG ]]; then
    conda install -q anaconda-client;
    anaconda -t $ANACONDA_TOKEN upload -u insilichem $HOME/miniconda/conda-bld/**/ommprotocol-*.tar.bz2;
  fi;

before_deploy:
- conda install constructor;
- conda remove --force constructor;
- pip install -U --no-deps https://github.com/jaimergp/constructor/archive/jinja-env.zip;
- constructor . ;

deploy:
# Deploy to PyPI
- provider: pypi
  username: jaimergp
  skip_cleanup: true
  password:
    secure: al4NX0/MIP0IDu7IcMKlKi6ySWTSNNxiM2DcOJROnqcyAOtC5+r+j+VmB03YZxLXw8+czUxDWorORRXmOsHTw29+BRWLBKJAjLUQw2QYMlf/0tCkrvpKvMG+OY9w1dxOVBOb3atme9IjQn6QDlMdu30sw8vaHudNEOMD6uspCRFngW4mjFAgTwgm2Bxs9Kmyeo83oVArdPDXU7ww1T7Jc6mKxX2e2YGjCGoVLrgsIZIJZOyxFRynwvZsYmjyLxKsQ82WbAaKptNdes4K0ihfQAwTDECGnFDzjU8TxonwaXpKW/2rkJPxkb62MdpDnWD5NtatrJ1oqx0tUILBLriUpQaRA2qR9pApBmsehQesC/z4jaNPmQqs8/he6SCPuEMneiICsCouwJOEcRD2MCdhRdFyfzVWdmcZI9Lf8jyMq/cHWwfKWGuIM/PVClMwupDrvJxcGkoXN/T+mWTaXPRNTPBcldq7GDBhKxm6vWUHPJOyS/w4/9lQs91sENVd6CBPzM8EcX4nV0JkjYKoGxuO2tEwa3LUihbgnpr2QdckYjxRUp8VLUW825886vrZSfRRTjfJp6d9EBLa4FC6YOezwxeotaquVmkMLjDPnboAEbQjbUicSSOaqKUDvjD+jxdnxc9KAKEDUEiXIIzx8wPO2JmoESeqg6hlYWntjqk2/tM=
  on:
    tags: true
    condition: "$MYCONDAPY = 3.6 && $TRAVIS_OS_NAME = linux"
#Deploy to GitHub releases
- provider: releases
  api_key:
    secure: fJMzrHDGscgyCcr93zMBqFmf6jJEeDJjUTFg75PVPOI5YpEGMmJujXZpyocIW9PVOWeso+gG7H0SQWBDEv8ptSGu43GO8nipFvSrJxcR+tQOP5Vosl/xvDLq+B4fPPf3ZvjQC70+lppjHubOY2UaPjnuOyuZvtcmEGZ+NGh3Oq5B31im9bgekhpzmvzmOt0i9uc/hKCH9m7QlRTEdVDAfxuuzILjqadBU2k70MiIvLqLkGcQzOv8jF0bqQOBUD81p49vzLK1Pjuv6j5s+GDd+Kb4jlwZ7EF+lfPGVZXob91wk1m4bIAlaj8wAlIXS/tqgM8qrlYJHHVb8arOYmt/KWawuGoSmpes7wqkJOX/BypFGDatqyWll+LkAuKU4uy9LkNvPBPiVOgw7FIScEH5r8tMLABhHWVcwbW6iG2NM1qDOdLQvbu6lR07AgQApkBtIT7ZEcKg2dehiIilV/5FZX68NDsenND+D90Gyu8WZZFS48uKkxH/ETAbMdBQRbgtaIIHFX+P07wrWeS9yQMSp4CKq9yQfz8FiWeQs7q/XixyUf/YjuhdF70sXb0WHdMEiAjyvpuYOxnyrS8aW2VZ54EAYgzrt3tPMcquvm4/rRqfPycx5BIdHYAn/BBbU2d4MSmCWy4/SOyGc5slCdw2xazg2gqElDcIlmV5J3wx+D8=
  file_glob: true
  file: ommprotocol-**.sh
  name: OMMProtocol ${TRAVIS_TAG}
  body: ${TRAVIS_COMMIT_MESSAGE}
  draft: false
  prerelease: false
  skip_cleanup: true
  on:
    tags: true
    repo: insilichem/ommprotocol
    condition: "$MYCONDAPY = 3.6"
