package:
  name: ommprotocol
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

about:
  home: https://github.com/insilichem/ommprotocol
  license: LGPL
  summary: Easy to deploy MD protocols for OpenMM

source:
  path: ../../

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - ommprotocol = ommprotocol:run_protocol
    - ommanalyze = ommprotocol.analyze:main
    - state2pdb = ommprotocol:state_to_pdb
    - exportframe = ommprotocol:export_frame

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - nomkl  # [unix]
    - openmm
    - ruamel_yaml
    - parmed
    - openmoltools
    - mdtraj
    - netcdf4
    - jinja2
    - pdbfixer
    - menuinst # [win]
    # These are for ommanalyze
    - matplotlib
    - tqdm
    - pandas

test:
  requires:
    - gromacs  # [unix]
    - pytest

  imports:
    - ommprotocol

  source_files:
    - tests

  commands:
    - ommprotocol -h
    - ommanalyze -h
    - pytest tests
